// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqYw4E3kaF_3TGfzgCBGwXCODhWHln-wo',
    appId: '1:628229261562:web:9fe0550ccaf1630ae6a143',
    messagingSenderId: '628229261562',
    projectId: 'class-flutter-d3c1b',
    authDomain: 'class-flutter-d3c1b.firebaseapp.com',
    storageBucket: 'class-flutter-d3c1b.firebasestorage.app',
    measurementId: 'G-KLGPZWZKFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfpGYjpe1-KAUm9hmXZlX-U7PIx-E_CDc',
    appId: '1:628229261562:android:d6c0eaef294fa585e6a143',
    messagingSenderId: '628229261562',
    projectId: 'class-flutter-d3c1b',
    storageBucket: 'class-flutter-d3c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYfINhjgmJ8LZV-IWZibmbQaQsuge-6fU',
    appId: '1:628229261562:ios:8e35404a1558d6cfe6a143',
    messagingSenderId: '628229261562',
    projectId: 'class-flutter-d3c1b',
    storageBucket: 'class-flutter-d3c1b.firebasestorage.app',
    iosClientId: '628229261562-ejpuss011p3tj3ucgkc4gklfeof4sevr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYfINhjgmJ8LZV-IWZibmbQaQsuge-6fU',
    appId: '1:628229261562:ios:8e35404a1558d6cfe6a143',
    messagingSenderId: '628229261562',
    projectId: 'class-flutter-d3c1b',
    storageBucket: 'class-flutter-d3c1b.firebasestorage.app',
    iosClientId: '628229261562-ejpuss011p3tj3ucgkc4gklfeof4sevr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqYw4E3kaF_3TGfzgCBGwXCODhWHln-wo',
    appId: '1:628229261562:web:7c88d281524f8ac4e6a143',
    messagingSenderId: '628229261562',
    projectId: 'class-flutter-d3c1b',
    authDomain: 'class-flutter-d3c1b.firebaseapp.com',
    storageBucket: 'class-flutter-d3c1b.firebasestorage.app',
    measurementId: 'G-Y721GLEW84',
  );
}
